branches:
   except: /\+$/

language: node_js
node_js:
 - "0.11"
 - "0.10"
#- "0.8"

before_install:
 - git clone https://github.com/Paws/Rulebook.git ./Test/Rulebook

script:
 - npm run-script test

after_success:
 - npm run-script coveralls

matrix:
   allow_failures:
#   - node_js: "0.8"

notifications:
   email: false
   irc:
      skip_join: true
      on_success: never
      on_failure: change
      channels:
       - "chat.freenode.net#ELLIOTTCABLE"
       - "chat.freenode.net#Paws.Nucleus"
      template:
       - "%{repository_name}/%{branch} @%{commit} %{author}: #%{build_number} %{message}"
       - "(Details: %{build_url})"
   slack:
      secure: "KTSaXaGAug+R8boN522JxPVXQaFiAKyebVvANcRGRCJPajEz12Dd3jo8aoE4r8zVFuuHUs8gQsOJoAu3w2j5FJo1ECq5OioPQqtYX7nJ6brtf/zVA2VTHmFueTeialOkNabhHJx+2Eh4J7JPVIb7MiLzaKqSLWHKHoB48HMaTCE="
